### ISSUE TITLE
No syntax highlighting for match-case statements

### ISSUE THREAD

**Issue by asxlvm** [tree-sitter/tree-sitter-python#141] opened 2021-12-06 22:33 UTC
I've got `coc-pyright` and Treesitter installed, just installed the Python language in Treesitter because I thought I'd get match-case statement syntax highlighting but I didn't, it made changes, but not to match-case statements.
![IMG_20211206_231436](https://user-images.githubusercontent.com/81298611/144933429-3dd5e981-7b98-4285-8cdb-0c6efb9f63ff.jpg)

**Comment by theHamsta** [comment] 2021-12-06 22:51
Duplicate of #116 ? You can test my PR if you want https://github.com/tree-sitter/tree-sitter-python/pull/140. Just change then SHA in nvim-treesitter/lockfile.json to the SHA of the branch in the PR and run TSUpdate. There's also an open PR at nvim-treesitter to highlight `match`/`case`

**Comment by doolio** [comment] 2022-09-27 04:43
This is also the case for me (using python 3.9.2 and python-lsp-server if that matters). Highlighting and indentation (though is this provided by tree-sitter?) not working as expected.

```
match subject:  # match keyword highlighted
    case <pattern_1>:  # case keyword highlighted; not indented as expected
        <action_1>  # not indented as expected
    case <pattern_2>:  # case keyword NOT highlighted; not indented as expected
        <action_2>  # not indented as expected
    case <pattern_3>:  # case keyword NOT highlighted; not indented as expected
        <action_3>  # not indented as expected
    case _:  # case keyword NOT highlighted; not indented as expected
        <action_wildcard>  # not indented as expected
```

**Comment by SadCheeto** [comment] 2023-03-20 10:57
I am running into the same problem - Is there any update on this issue? The grammar documentation for python 3 suggests that match statements are supported, so I was just wondering if there was a reason behind this branch not being merged into main? (docs: https://docs.python.org/3/reference/grammar.html)

**Closed** 2023-07-11 03:50 UTC
