### ISSUE TITLE
Comments at the end of a function are parsed as if they're outside the function

### ISSUE THREAD

**Issue by giovannitangredi** [tree-sitter/tree-sitter-python#142] opened 2021-12-10 14:40 UTC
Comments at the end of a function are parsed like they are outside the function scope/space.
For Example:
``` 
def function():
    a=3 # comment
        # inside
    b=4 # comment
        # outside
``` 
Will parse a function node that terminates immediately after the assignment `b=4`.
The parsing tree is like this:
``` 
(module [0, 0] - [4, 17]
  (function_definition [0, 0] - [3, 7]
    name: (identifier [0, 4] - [0, 12])
    parameters: (parameters [0, 12] - [0, 14])
    body: (block [1, 4] - [3, 7]
      (expression_statement [1, 4] - [1, 7]
        (assignment [1, 4] - [1, 7]
          left: (identifier [1, 4] - [1, 5])
          right: (integer [1, 6] - [1, 7])))
      (comment [1, 8] - [1, 17])
      (comment [2, 8] - [2, 16])
      (expression_statement [3, 4] - [3, 7]
        (assignment [3, 4] - [3, 7]
          left: (identifier [3, 4] - [3, 5])
          right: (integer [3, 6] - [3, 7])))))
  (comment [3, 8] - [3, 17])
  (comment [4, 8] - [4, 17]))
```
Instead of the expected result that should be this one: 
```
(module [0, 0] - [4, 17]
  (function_definition [0, 0] - [3, 7]
    name: (identifier [0, 4] - [0, 12])
    parameters: (parameters [0, 12] - [0, 14])
    body: (block [1, 4] - [3, 7]
      (expression_statement [1, 4] - [1, 7]
        (assignment [1, 4] - [1, 7]
          left: (identifier [1, 4] - [1, 5])
          right: (integer [1, 6] - [1, 7])))
      (comment [1, 8] - [1, 17])
      (comment [2, 8] - [2, 16])
      (expression_statement [3, 4] - [3, 7]
        (assignment [3, 4] - [3, 7]
          left: (identifier [3, 4] - [3, 5])
          right: (integer [3, 6] - [3, 7])))))
      (comment [3, 8] - [3, 17])
      (comment [4, 8] - [4, 17]))
```

**Comment by stsewd** [comment] 2021-12-11 22:09
Hi, this is a duplicate of https://github.com/tree-sitter/tree-sitter-python/issues/113

**Closed** 2021-12-12 18:09 UTC
